# Generated by Django 5.1.7 on 2025-05-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='coursecode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
